-- Add sample manga products to database
-- Run this in Supabase SQL Editor

-- Check existing manga
SELECT id, title, price FROM manga LIMIT 5;

-- Insert sample manga if they don't exist
INSERT INTO manga (
  title,
  author,
  publisher,
  volume,
  price,
  original_price,
  discount_percentage,
  image,
  description,
  stock_count,
  rating,
  reviews_count,
  pages,
  release_date,
  genre,
  is_featured,
  is_new,
  created_at,
  updated_at
) 
VALUES 
  (
    'One Piece Vol. 1',
    'Eiichiro Oda',
    'Shueisha',
    1,
    9.99,
    12.99,
    23,
    '/manga/one-piece-1.jpg',
    'Join Monkey D. Luffy as he begins his quest to become King of the Pirates!',
    50,
    5.0,
    1250,
    216,
    '1997-07-22',
    'Adventure, Action',
    true,
    false,
    NOW(),
    NOW()
  ),
  (
    'Naruto Vol. 1',
    'Masashi Kishimoto',
    'Shueisha',
    1,
    8.99,
    11.99,
    25,
    '/manga/naruto-1.jpg',
    'The story of Naruto Uzumaki, a young ninja who seeks recognition and dreams of becoming the Hokage!',
    45,
    4.8,
    890,
    192,
    '1999-09-21',
    'Action, Adventure',
    true,
    false,
    NOW(),
    NOW()
  ),
  (
    'Attack on Titan Vol. 1',
    'Hajime Isayama',
    'Kodansha',
    1,
    10.99,
    13.99,
    21,
    '/manga/aot-1.jpg',
    'Humanity fights for survival against man-eating Titans!',
    30,
    4.9,
    1500,
    200,
    '2009-09-09',
    'Dark Fantasy, Action',
    true,
    true,
    NOW(),
    NOW()
  ),
  (
    'My Hero Academia Vol. 1',
    'Kohei Horikoshi',
    'Shueisha',
    1,
    9.99,
    12.99,
    23,
    '/manga/mha-1.jpg',
    'In a world where most humans have superpowers, Izuku Midoriya dreams of becoming a hero!',
    40,
    4.7,
    750,
    192,
    '2014-07-07',
    'Superhero, Action',
    false,
    true,
    NOW(),
    NOW()
  ),
  (
    'Demon Slayer Vol. 1',
    'Koyoharu Gotouge',
    'Shueisha',
    1,
    9.99,
    12.99,
    23,
    '/manga/demon-slayer-1.jpg',
    'Tanjiro becomes a demon slayer to save his sister and avenge his family!',
    35,
    5.0,
    2100,
    192,
    '2016-02-15',
    'Dark Fantasy, Action',
    true,
    true,
    NOW(),
    NOW()
  ),
  (
    'Jujutsu Kaisen Vol. 1',
    'Gege Akutami',
    'Shueisha',
    1,
    9.99,
    12.99,
    23,
    '/manga/jjk-1.jpg',
    'Yuji Itadori joins a secret organization to eliminate cursed spirits!',
    28,
    4.8,
    980,
    192,
    '2018-03-05',
    'Dark Fantasy, Action',
    true,
    true,
    NOW(),
    NOW()
  ),
  (
    'Chainsaw Man Vol. 1',
    'Tatsuki Fujimoto',
    'Shueisha',
    1,
    9.99,
    12.99,
    23,
    '/manga/chainsaw-man-1.jpg',
    'Denji merges with his pet devil Pochita to become Chainsaw Man!',
    25,
    4.9,
    1200,
    192,
    '2018-12-03',
    'Dark Fantasy, Horror',
    false,
    true,
    NOW(),
    NOW()
  ),
  (
    'Tokyo Revengers Vol. 1',
    'Ken Wakui',
    'Kodansha',
    1,
    10.99,
    13.99,
    21,
    '/manga/tokyo-revengers-1.jpg',
    'Takemichi travels back in time to save his girlfriend from a tragic fate!',
    20,
    4.6,
    650,
    192,
    '2017-03-01',
    'Action, Drama',
    false,
    false,
    NOW(),
    NOW()
  )
ON CONFLICT DO NOTHING;

-- Verify insertion
SELECT COUNT(*) as total_manga FROM manga;
SELECT title, price, stock_count FROM manga ORDER BY created_at DESC LIMIT 10;
